// Import the Inter font from Google Fonts
import { Inter } from 'next/font/google';
// Import global CSS styles
import './globals.css';

// Configure Inter font with Latin subset
const inter = Inter({ subsets: ['latin'] });

/**
 * Metadata configuration for the Next.js application
 * Controls SEO-related tags in the document head
 */
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/**
 * RootLayout Component
 * Serves as the base layout wrapper for all pages in the Next.js application
 * Adds consistent styling, fonts, and structure across the entire app
 *
 * @param {Object} props - Component props
 * @param {React.ReactNode} props.children - Child components/pages to be rendered inside the layout
 * @returns {JSX.Element} The root HTML structure for the application
 */
export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        {/* Render the page content */}
        {children}

        {/* Copyright footer that appears on all pages */}
        <p className='text-xs bg-black text-white'>
          Created by Aadivya Raushan © 2024
        </p>
      </body>
    </html>
  );
}
